# $FreeBSD$

PORTNAME=	    dj-database-url
PORTVERSION=	0.4.1
CATEGORIES=	    www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	pewright@tronc.com
COMMENT=	Use Database URLs in your Django Application.

LICENSE=	BSD
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		python:2.7+
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
