# $FreeBSD$

PORTNAME=	greeking
PORTVERSION=	2.2.0
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	pewright@tronc.com
COMMENT=	Django template tools for printing filler, a technique from the days of hot type known as greeking.

NO_ARCH=	yes
USES=		python:2.7+
USE_PYTHON=	autoplist distutils

RUN_DEPENDS=    ${PYTHON_PKGNAMEPREFIX}six>1.5.2:devel/py-six

.include <bsd.port.mk>
