# $FreeBSD$

PORTNAME=	newrelic
PORTVERSION=	2.78.0.57
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	pewright@tronc.com
COMMENT=	The newrelic package instruments your application for performance monitoring and advanced performance analytics with New Relic.

NO_ARCH=	yes
USES=		python:2.7+
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
