# $FreeBSD$

PORTNAME=	tinys3
PORTVERSION=	0.1.12
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	pewright@tronc.com
COMMENT=	A small library for uploading files to S3,With support of async uploads, worker pools, cache headers etc

NO_ARCH=	yes
USES=		python:2.7+
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
